apiVersion: v1
kind: Service
metadata:
  name: mt-client-svc
  namespace: ingress
spec:
  selector:
    app: mt-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP